### ISSUE TITLE
Session DocType ToDo.

### ISSUE THREAD

**Issue by achillesrasquinha** [frappe/frappejs#19]
- [ ] Render form object using User Session + Session DocType (JS + HTML)
- [ ] Cookie Management.
- [ ] Binary Permissions (No Permissions yet with Session ID).
- [ ] Session Creation by Guests (else Logged in with Cookies).
- [ ] Session using Public Private
